import { Language } from "./types";
import { cleanWordMarkup } from "./word";

export function cleanHtml(
    html: string,
    language: Language
): string {
    html = html
        .replace(/\s+(;|!|,|\)|\]|})/g, "$1")
        .replace(/(\(|\[|\{)\s+/g, "$1")
        .replace(/(&nbsp;)+\./g, ".")
        .replace(/(&nbsp;)*<br>/g, "<br>")
        .replace(/(&nbsp;)*<br \/>/g, "<br />")
        .replace(/(\w)\s*<\/h(\d)>/g, "$1</h$2>")
        .replace(/<h(\d)>\s*([\w(])/g, "<h$1>$2")
        .replace(/\s*<\/h(\d)>/g, "</h$1>")
        .replace(/(\d*)\sh\s(\d*)/g, "$1&nbsp;h&nbsp;$2")
        .replace(/<\/i>(\s*)<i>/g, "$1")
        .replace(/<\/em>(\s*)<em>/g, "$1")
        .replace(/<\/b>(\s*)<b>/g, "$1")
        .replace(/<\/strong>(\s*)<strong>/g, "$1")
        .replace(/<b>(\s*)<\/b>/g, "$1")
        .replace(/<strong>\s*<\/strong>/g, "")
        .replace(/<b>(&nbsp;)*<\/b>/g, "&nbsp;")
        .replace(/<strong>(&nbsp;)*<\/strong>/g, "&nbsp;")
        .replace(/(<br>)*\s*<br>\s*<\/b>/g, "</b>$1<br>")
        .replace(/(<br \/>)*\s*<br \/>\s*<\/b>/g, "</b>$1<br \/>")
        .replace(/(<br>)*\s*<br>\s*<\/strong>/g, "</b>$1<br>")
        .replace(/(<br \/>)*\s*<br \/>\s*<\/strong>/g, "</b>$1<br \/>")
        .replace(/ (\s+)/g, " ")
        .replace(/(\s+)<br>/g, "<br>")
        .replace(/(\s+)<br \/>/g, "<br \/>")
        .replace(/<br>(\s+)/g, "<br>")
        .replace(/<br \/>(\s+)/g, "<br \/>")
        .replace(/(\s+)<\/a>/g, "</a> ")
        .replace(/"(\s+)>/g, '">');

    html = language === "eng"
        ? html.replace(/(name="_msoanchor_\d+">\[[^\]]+\]<\/a>)&nbsp;/g, "$1")
        : html.replace(/(name="_msoanchor_\d+">\[[^\]]+\]<\/a>)&nbsp;(?![:–])/g, "$1");

    html = html
        .replace(/(&nbsp;)+/g, "&nbsp;")
        .replace(/&nbsp;<\/p/g, "</p")
        .replace(/<a name="([^"]*)">(.*?)<\/a>/g, "$2")
        .replace(/<\/b>&nbsp;:/g, "&nbsp;:</b>")
        .replace(/<\/b>:/g, ":</b>")
        .replace(/<\/strong>&nbsp;:/g, "&nbsp;:</strong>")
        .replace(/<\/strong>:/g, ":</strong>")
        .replace(/<b>\s+/g, " <b>")
        .replace(/\s+<\/b>/g, "</b> ")
        .replace(/<strong>\s+/g, " <strong>")
        .replace(/\s+<\/strong>/g, "</strong> ")
        .replace(/<b>&nbsp;+/g, "&nbsp;<b>")
        .replace(/&nbsp;+<\/b>/g, "</b>&nbsp;")
        .replace(/<strong>&nbsp;+/g, "&nbsp;<strong>")
        .replace(/&nbsp;+<\/strong>/g, "</strong>&nbsp;")
        .replace(/<em>\s+/g, " <em>")
        .replace(/\s+<\/em>/g, "</em> ")
        .replace(/<em>&nbsp;+/g, "&nbsp;<em>")
        .replace(/&nbsp;+<\/em>/g, "</em>&nbsp;")
        .replace(/\s+<\/p/g, "</p")
        .replace(/&nbsp;<\/li/g, "</li")
        .replace(/\s+<\/li/g, "</li")
        .replace(/\s+<\/i>/g, "</i> ")
        .replace(/<i>\s+/g, " <i>")
        .replace(/\s+<\/cite>/g, "</cite> ")
        .replace(/<cite>\s+/g, " <cite>")
        .replace(/&nbsp; /g, " ")
        .replace(/ &nbsp;/g, " ")
        .replace(/&nbsp;\?/g, "?")
        .replace(/ \?/g, "?")
        .replace(/\s+<\/td>/g, "</td>")
        .replace(/&nbsp;+<\/td>/g, "</td>")
        .replace(/\s+<\/th>/g, "</th>")
        .replace(/&nbsp;+<\/th>/g, "</th>")
        .replace(/ border="(\d+)"/g, "")
        .replace(/ cellspacing="(\d+)"/g, "")
        .replace(/ cellpadding="(\d+)"/g, "")
        .replace(/ width="(\d+)\%*"/g, "")
        .replace(/ valign="(\w+)"/g, "")
        .replace(/ nowrap/g, "")
        .replace(/ border="(\d+)" cellspacing="(\d+)" cellpadding="(\d+)"/g, ' class="table table-bordered"')
        .replace(/<table>/g, '<table class="table table-bordered">')
        .replace(/<table((?:(?!<tr class="active").|\n)*?)<tr>/g, '<table$1<tr class="active">')
        .replace(/ height="(\d+)"/g, "")
        .replace(/ size="(\d+)"/g, "")
        .replace(/ style="[^"]*"/g, "")
        .replace(/<span>([^<]*)<\/span>/g, "$1")
        .replace(/ align="center"/g, "")
        .replace(/ align="left"/g, "")
        .replace(/ align="right"/g, "")
        .replace(/ title="[^"]*"/g, "")
        .replace(/<br clear="all">\s*/gi, "")
        .replace(/(\s*)<\/p>/g, "</p>")
        .replace(/<p>(\s*)/g, "<p>")
        .replace(/(\s*)<\/td>/g, "</td>")
        .replace(/<td>(\s*)/g, "<td>")
        .replace(/(\s*)<\/th>/g, "</th>")
        .replace(/<th>(\s*)/g, "<th>")
        .replace(/<td>(\s*)<\/td>/g, "<td></td>")
        .replace(/(\s+)\./g, ".")
        .replace(/<b>(\s*)<b>/g, "<b>$1")
        .replace(/<\/b>(\s*)<\/b>/g, "</b>$1")
        .replace(/<strong>(\s*)<strong>/g, "<strong>$1")
        .replace(/<\/strong>(\s*)<\/strong>/g, "</strong>$1")
        .replace(/<u><a(\s*\S*)>/g, "<a$1>")
        .replace(/<\/a><\/u>/g, "</a>")
        .replace(/<a(.*)"><u>/g, '<a$1">')
        .replace(/<\/u><\/a>/g, "</a>")
        .replace(/<u><b>/g, "<b>")
        .replace(/<\/b><\/u>/g, "</b>")
        .replace(/<b><u>/g, "<b>")
        .replace(/<\/u>(:)?<\/b>/g, "$1</b>")
        .replace(/<u><strong>/g, "<strong>")
        .replace(/<\/strong<\/u>/g, "</strong>")
        .replace(/<strong><u>/g, "<strong>")
        .replace(/<\/u>(:)?<\/strong>/g, "$1</strong>")
        .replace(/<\/u>(\s*)<u>/g, "$1")
        .replace(/<i>\.<\/i>/g, ".")
        .replace(/<cite>\.<\/cite>/g, ".")
        .replace(/<cite><\/cite>/g, "")
        .replace(/<em>\.<\/em>/g, ".")
        .replace(/<em><\/em>/g, "")
        .replace(/<em>&nbsp;<\/em>/g, "&nbsp;")
        .replace(/<i>&nbsp;*<\/i>/g, " ")
        .replace(/<i><\/i>/g, "")
        .replace(/<h\d id="">&nbsp;*<\/h\d>\s*/g, "")
        .replace(/<div>\s*<\/div>\s*/g, "")
        .replace(/<div>&nbsp;*<\/div>\s*/g, "")
        .replace(/<b><\/b>/g, "")
        .replace(/<li><\/li>(\s+)/g, "")
        .replace(/<u>(&nbsp;)*<\/u>/g, "")
        .replace(/<u>\s*<\/u>/g, "")
        .replace(/<p>(\s*)<\/p>/g, "")
        .replace(/<p><em>&nbsp;<\/em><\/p>/g, "")
        .replace(/<p>&nbsp;+/g, "<p>")
        .replace(/<p>&nbsp;<\/p>/g, "")
        .replace(/<h\d>(&nbsp;*|\s*)<\/h\d>\s*/g, "")
        .replace(/(\s+):/g, "&nbsp;:")
        .replace(/ »/g, "&nbsp;»")
        .replace(/« /g, "«&nbsp;");

    if (language === "fra") {
        html = html
            .replace(/(?<=\b\d{1,3}) (?=\d{3}(?:\b| ))/g, "&nbsp;")
            .replace(/(?<=\b\d{1,3}) (?=\$)/g, "&nbsp;");
    }

    html = html
        .replace(/<p><br>\s*/g, "<p>")
        .replace(/<p><br \/>\s*/g, "<p>")
        .replace(/<p><strong><br \/>\s*/g, "<p><strong>")
        .replace(/<p><b><br \/>\s*/g, "<p><b>")
        .replace(/<br><\/b><\/p>/g, "</b></p>")
        .replace(/<p><br>/g, "<p>")
        .replace(/<br><\/p>/g, "</p>")
        .replace(/<\/p>\s*<br>/g, "</p>")
        .replace(/<br \/><\/b><\/p>/g, "</b></p>")
        .replace(/<p><br \/>/g, "<p>")
        .replace(/<br \/><\/p>/g, "</p>")
        .replace(/<\/p>\s*<br \/>/g, "</p>")
        .replace(/<br>(\s*)<\/p>/g, "</p>")
        .replace(/<br \/>(\s*)<\/p>/g, "</p>")
        .replace(/ type="a"/g, ' class="lst-lwr-alph"')
        .replace(/ type="circle"/g, "")
        .replace(/ type="disc"/g, "")
        .replace(/ type="square"/g, "")
        .replace(/ type="1"/g, "")
        .replace(/(\s*)<ul>(\s*)<ul>/g, "<ul>")
        .replace(/(\s*)<ul>(\s*)<ul>/g, "<ul>")
        .replace(/(\s*)<ol>(\s*)<ol>/g, "<ol>")
        .replace(/<\/ul>(\n*)(\s*)<\/ul>/g, "</ul>")
        .replace(/<\/ol>(\n*)(\s*)<\/ol>/g, "</ol>")
        .replace(/(\s*)<\/ol>(\n*)(\s*)<ol>/g, "")
        .replace(/(\s*)<\/ul>(\n*)(\s*)<ul>/g, "")
        .replace(/<li>(\s+)/g, "<li>")
        .replace(/<li><a href="(.*)"> /g, '<li><a href="$1">')
        .replace(/(\s*)<\/li>(\n*)(\s*)<ol/g, "\n<ol")
        .replace(/(\s*)<\/li>(\n*)(\s*)<ul>/g, "\n<ul>")
        .replace(/<\/ol>(\s*)<li>/g, "</ol>\n</li>\n<li>")
        .replace(/<\/ul>(\s*)<li>/g, "</ul>\n</li>\n<li>")
        .replace(/<\/(\w)l>\s*<\/(\w)l>/g, "</$1l>\n</li>\n</$2l>")
        .replace(/<li><\/li>/g, "")
        .replace(/<ol><\/ol>/g, "")
        .replace(/<ul><\/ul>/g, "")
        .replace(/<h(\d)><strong>\s*/g, "<h$1>")
        .replace(/<h(\d)>\s*<strong>/g, "<h$1>")
        .replace(/<h(\d) id=".*"><strong>\s*/g, "<h$1>")
        .replace(/<\/strong><\/h(\d)>\s*/g, "</h$1>")
        .replace(/<\/strong>\s*<\/h(\d)>/g, "</h$1>")
        .replace(/<a href="#_Toc(\d+)">/g, '<a href="#toc">')
        .replace(/<a href="#_bookmark(\d+)">/g, '<a href="#toc">')
        .replace(/\.\.\.\.\.*\s*\d+<\/a>/g, "</a>")
        .replace(/\.\.\.\.\.*\s*\d+/g, "")
        .replace(/ target="_blank"/g, "")
        .replace(/ target="blank"/g, "")
        .replace(/ (\s+)/g, " ")
        .replace(/\n+/g, "\n")
        .replace(/<\/p>/g, "</p>\n")
        .replace(/<\/p>\n<\/li>/g, "</p></li>")
        .replace(/ /g, " ")
        .replace(/(January|February|March|April|May|June|July|August|September|October|November|December) (\d+)/g, "$1&nbsp;$2")
        .replace(/(\d+) (janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)/g, "$1&nbsp;$2")
        .replace(/(1er) (janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)/g, "1er&nbsp;$2")
        .replace(/(January|February|March|April|May|June|July|August|September October|November|December) 20(\d{2})/g, "$1&nbsp;20$2")
        .replace(/(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre) 20(\d{2})/g, "$1 20$2")
        .replace(/(\d+)\s+hours/g, "$1&nbsp;hours")
        .replace(/(\d+)\s+heures/g, "$1&nbsp;heures")
        .replace(/<p><strong>Table of contents<\/strong><\/p>/gi, "<h2>Table of contents</h2>")
        .replace(/<p><strong>Table des matières<\/strong><\/p>/gi, "<h2>Table des matières</h2>")
        .replace(/<h3>Table of contents<\/h3>/gi, "<h2>Table of contents</h2>")
        .replace(/<h3>Table des matières<\/h3>/gi, "<h2>Table des matières</h2>")
        .replace(/<p>Table of contents<\/p>/gi, "<h2>Table of contents</h2>")
        .replace(/<p>Table des matières<\/p>/gi, "<h2>Table des matières</h2>")
        .replace(/<p><strong>On this page<\/strong><\/p>/gi, "<h2>On this page</h2>")
        .replace(/<p><strong>Sur cette page<\/strong><\/p>/gi, "<h2>Sur cette page</h2>")
        .replace(/<h3>On this page<\/h3>/gi, "<h2>On this page</h2>")
        .replace(/<h3>Sur cette page<\/h3>/gi, "<h2>Sur cette page</h2>")
        .replace(/(\n)(\n)<\/td>/g, "\n</td>")
        .replace(/<p><\/p>/g, "")
        .replace(/<p>&nbsp;<\/p>/g, "")
        .replace(/<li>(\s+)/g, "<li>")
        .replace(/\s*<\/h(\d)>/g, "</h$1>")
        .replace(/ (\s+)/g, " ")
        .replace(/ ( +)/g, " ")
        .replace(/( +) /g, " ")
        .replace(/<br>(&nbsp;)*/g, "<br>")
        .replace(/<br \/>(&nbsp;)*/g, "<br />")
        .replace(/ <\/strong><\/p/g, "</strong></p")
        .replace(/&nbsp;<\/strong><\/p/g, "</strong></p")
        .replace(/<br \/><\/strong>/g, "</strong><br />")
        .replace(/<br><\/strong>/g, "</strong><br>")
        .replace(/(&nbsp;*)<\/p>/g, "</p>")
        .replace(/(&nbsp;*)<\/h(\d)>/g, "</h$2>")
        .replace(/<h(\d)>\s*(\w)/g, "<h$1>$2")
        .replace(/<p><strong><\/strong><\/p>/g, "")
        .replace(/\s+<\/td>/g, "</td>")
        .replace(/&nbsp;+<\/td>/g, "</td>")
        .replace(/\s+<\/th>/g, "</th>")
        .replace(/&nbsp;+<\/th>/g, "</th>")
        .replace(/<h(\d)>(<br \/>|\n)*/g, "<h$1>")
        .replace(/^[\s]+/g, "")
        .replace(/<h(\d)>\s*(\w)/g, "<h$1>$2")
        .replace(/&Agrave;/g, "À").replace(/&agrave;/g, "à")
        .replace(/&Ccedil;/g, "Ç").replace(/&ccedil;/g, "ç")
        .replace(/&Egrave;/g, "È").replace(/&egrave;/g, "è")
        .replace(/&Eacute;/g, "É").replace(/&eacute;/g, "é")
        .replace(/&Ecirc;/g, "Ê").replace(/&ecirc;/g, "ê")
        .replace(/&Icirc;/g, "Î").replace(/&icirc;/g, "î")
        .replace(/&Iuml;/g, "Ï").replace(/&iuml;/g, "ï")
        .replace(/&Ocirc;/g, "Ô").replace(/&ocirc;/g, "ô")
        .replace(/&oelig;/g, "œ").replace(/&OElig;/g, "Œ")
        .replace(/&Ugrave;/g, "Ù").replace(/&ugrave;/g, "ù")
        .replace(/&Ucirc;/g, "Û").replace(/&ucirc;/g, "û")
        .replace(/&laquo;/g, "«").replace(/&raquo;/g, "»")
        .replace(/&rsquo;/g, "’").replace(/&ldquo;/g, "“").replace(/&rdquo;/g, "”")
        .replace(/<\/ul>(\n*)<p/g, "</ul>\n\n<p")
        .replace(/<\/p>(\n*)<p/g, "</p>\n\n<p")
        .replace(/<\/ul>(\n*)<h/g, "</ul>\n\n<h")
        .replace(/<\/ol>(\n*)<p/g, "</ol>\n\n<p")
        .replace(/<\/table>(\n*)<h/g, "</table>\n\n<h")
        .replace(/<\/table>(\n*)<p/g, "</table>\n\n<p")
        .replace(/<\/p>(\n*)<table/g, "</p>\n\n<table")
        .replace(/<\/p>(\n*)<h(\d)/g, "</p>\n\n<h$2")
        .replace(/<\/h(\d)>(\n*)<ul/g, "</h$1>\n\n<ul")
        .replace(/<\/h(\d)>(\n*)<ol/g, "</h$1>\n\n<ol")
        .replace(/<\/h(\d)>(\n*)<p/g, "</h$1>\n\n<p")
        .replace(/<\/h(\d)>(\n*)<table/g, "</h$1>\n\n<table")
        .replace(/<\/h(\d)>(\n*)<h(\d)/g, "</h$1>\n\n<h$3")
        .replace(/\n <h(\d)/g, "\n<h$1")
        .replace(/\n <div/g, "\n<div")
        .replace(/<br \/>\n*/g, "<br />")
        .replace(/<br \/>/g, "<br />\n")
        .replace(/<br>\n*/g, "<br>")
        .replace(/<br>>/g, "<br>\n")
        .replace(/\n<li/g, "\n\t<li")
        .replace(/\n<thead/g, "\n\t<thead")
        .replace(/\n<\/thead/g, "\n\t</thead")
        .replace(/\n<tbody/g, "\n\t<tbody")
        .replace(/\n<\/tbody/g, "\n\t</tbody")
        .replace(/\n<tr/g, "\n\t\t<tr")
        .replace(/\n<\/tr/g, "\n\t\t</tr")
        .replace(/\n<td/g, "\n\t\t\t<td")
        .replace(/\n<th/g, "\n\t\t\t<th")
        .replace(/<br><br><\/p>/g, "</p>")
        .replace(/&nbsp;<\/li>/g, "</li>")
        .replace(/(<br>)*<\/li>/g, "</li>")
        .replace(/<br>(\s*)<\/p>/g, "</p>")
        .replace(/<br \/>(\s*)<\/p>/g, "</p>")
        .replace(/(\w)\s*<\/h(\d)>/g, "$1</h$2>")
        .replace(/<h(\d)>\s*([\w(])/g, "<h$1>$2")
        .replace(/\s*<\/h(\d)>/g, "</h$1>");

    return cleanWordMarkup(html).replace(/&nbsp;<\/p>/g, "</p>");
}